apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secret-store
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: d:/dapr_test/my-components/mysecrets.json
    - name: nestedSeparator
      value: ":"
