apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-redis-store
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: 192.168.75.80:6379
    - name: redisPassword
      value: 123456
    - name: enableTLS
      value: false
